---
- name: Checking hostname, Memory and HD
  hosts: 192.168.0.90
  gather_facts: True
  become: yes
  tasks:
  - name: checking for host name
    shell: hostname
    register: hostname  

  - name: Printing host name
    debug:
      msg: "{{hostname.stdout}}"

  - name: checking for server memory
    shell: cat /proc/meminfo
    register: memory

  - name: Printing memory usege
    debug:
      var: memory.stdout_lines
  
  - name: checking disk usege
    shell: df -h
    register: disk

  - name: Output for disk size
    debug:
      var: disk.stdout_lines

  - name: Checking CPU usage
    shell: cat /proc/cpuinfo
    register: cpu

  - name: Printing output of CPU
    debug:
      var: cpu.stdout_lines

  - name: Done
    script: /etc/ansible/figlet.sh
    register: done

  - name: Printing fanle msg
    debug:
      var: done.stdout_lines
