---
- name: VM from template 
  hosts: localhost
  gather_facts: false
  connection: local
  become: yes
  become_method: enable
  vars:
    count: 2
    vcenter_hostname: 192.168.0.4
    vcenter_user: administrator@vsphere.local
    vcenter_pass: Passwd@123
    esxhost: 192.168.0.205
    datastore: Homedata1
    custom_ip: 192.168.0.61
    vmtemplate: ct7tmp
    name: "TESTING3"
    custom_ip: 192.168.0.29
    vmtemplate: ct7temp
    notes: Ansible :Test
    folder: "/"
    dumpfacts: False
  tasks:
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxhost }}"
        datacenter: Datacenter1 
        name: "{{ name }}"
        folder: "{{ folder }}"
        template: "{{ vmtemplate }}"
        disk:
          - size_gb: "{{ disk_size | default(30) }}"
            type: thin
            datastore: "{{ datastore }}"
        networks:
        - name: VM Network
          type: static
          ip: "{{ custom_ip }}"
          netmask: 255.255.255.0
          gateway: 192.168.0.1
          dns_servers:
          - 192.168.0.1
          - 8.8.8.8
        hardware:
          memory_mb: "{{ vm_memory | default(1024) }}"
        wait_for_ip_address: True
        state: present 
      register: newvm
